apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-db-external-secret
  namespace: saas-app
spec:
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: saas-platform-prod-db-credentials-v1
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: saas-platform-prod-db-credentials-v1
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: saas-platform-prod-db-credentials-v1
        property: dbname
    - secretKey: DB_USER
      remoteRef:
        key: saas-platform-prod-db-credentials-v1
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: saas-platform-prod-db-credentials-v1
        property: password
    - secretKey: DB_ENGINE
      remoteRef:
        key: saas-platform-prod-db-credentials-v1
        property: engine
