apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saas-app

resources:
- ../../../k8s/base

patches:
- path: ingress-patch.yaml
- path: configmap-patch.yaml
- path: external-secret-patch.yaml
images:
- name: 700213287974.dkr.ecr.eu-west-1.amazonaws.com/saas-platform-prod-api
  newName: 700213287974.dkr.ecr.eu-west-1.amazonaws.com/saas-platform-prod-api
  newTag: 4942a8f536af472e52d9ba8571ceec302d144349
