{
 "title": "Dashboard Profesional en Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pods Activos en Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"saas-app\", condition=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia p95 (Segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace=\"saas-app\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS por Estado HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"saas-app\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}