# ==============================================================================
# Manifest / Manifiesto: k8s/base/db-secret.yaml
# Description: Kubernetes Secret for RDS PostgreSQL database connection
# Descripción: Secreto de Kubernetes para la conexión a la BD RDS PostgreSQL
# ==============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: app-db-credentials
  namespace: saas-app
type: Opaque
stringData:
  DB_ENGINE: "postgres"
  DB_HOST: "saas-platform-dev-db.cz20sak60eut.eu-west-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "appdb"
  DB_USER: "dbadmin"
  # NOTE: We will inject the password (DB_PASSWORD) via Secrets Manager or apply it as a variable during the pipeline deployment.
  # NOTA: La contraseña (DB_PASSWORD) la inyectaremos a través de Secrets Manager o la aplicaremos como variable durante el despliegue del pipeline.
  DB_PASSWORD: "TU_CONTRASEÑA_DE_RDS"