apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-db-external-secret
  namespace: saas-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: app-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: saas-platform-dev-db-credentials-v1
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: saas-platform-dev-db-credentials-v1
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: saas-platform-dev-db-credentials-v1
        property: dbname
    - secretKey: DB_USER
      remoteRef:
        key: saas-platform-dev-db-credentials-v1
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: saas-platform-dev-db-credentials-v1
        property: password
    - secretKey: DB_ENGINE
      remoteRef:
        key: saas-platform-dev-db-credentials-v1
        property: engine