apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- servicemonitor.yaml
- cluster-secret-store.yaml
- external-secret.yaml
images:
- name: 700213287974.dkr.ecr.eu-west-1.amazonaws.com/saas-platform-dev-api
  newName: 700213287974.dkr.ecr.eu-west-1.amazonaws.com/saas-platform-dev-api
  newTag: 57512cc4abd281cd357922fa1ab61ac5c7950ae6
