apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- servicemonitor.yaml
- cluster-secret-store.yaml
- external-secret.yaml
images:
- name: 700213287974.dkr.ecr.eu-west-1.amazonaws.com/saas-platform-dev-api
  newName: 700213287974.dkr.ecr.eu-west-1.amazonaws.com/saas-platform-dev-api
  newTag: d388ca6acd32cc583ea2e954a1fa8229d87d2b8c
