apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- servicemonitor.yaml
images:
- name: 700213287974.dkr.ecr.eu-west-1.amazonaws.com/saas-platform-dev-api
  newName: 700213287974.dkr.ecr.eu-west-1.amazonaws.com/saas-platform-dev-api
  newTag: 366ba720071da301490fe1a8e07575afe0b0e1d1
