apiVersion: v1
kind: ServiceAccount
metadata:
  name: saas-backend-sa
  namespace: saas-app
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::700213287974:role/saas-platform-prod-saas-app-irsa"
  labels:
    app.kubernetes.io/name: saas-backend
    app.kubernetes.io/component: backend
